version: "3.8"

services:
  app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - REFRESH_TOKEN=${REFRESH_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
